name: Deploy slides to pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["trunk"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install slidev
        run: npm install @slidev/cli --global
      - name: Install dependencies
        run: npm install
      - name: Build slides
        run: slidev build --base '/slidev-elixirconfeu-2023-lightening-talk-pbt/' pbt.md
      - name: Fix dist
        run: |
          mkdir ./dist/slidev-elixirconfeu-2023-lightening-talk-pbt
          cp -r ./dist/assets ./dist/slidev-elixirconfeu-2023-lightening-talk-pbt/assets
          cp -r ./dist/images ./dist/slidev-elixirconfeu-2023-lightening-talk-pbt/images
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Upload pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v1
